services:
  api:
    build:
      context: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - REDIS_QUEUE_URL=redis://:${REDIS_PASSWORD}@redis-queue:6379
      - LITELLM_BASE_URL=http://litellm:4000
    network_mode: "host"
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3000"
    network_mode: "host"
