-- ============================================================================
-- Seed: DACH universities from the hipo/university-domains-list dataset
--   (https://github.com/hipo/university-domains-list, static JSON snapshot).
--
-- Populates public.universities with name/country/email_domains for every
-- Germany/Austria/Switzerland entry (443 rows), so onboarding + email-domain
-- verification (link_university_email) work for students outside Marburg.
--
-- source='hipo', external_ref=<primary domain> (stable key across re-runs).
-- Idempotent: ON CONFLICT (source, external_ref) DO UPDATE.
--
-- Dedup guard: skips any hipo row whose email_domains overlap a university
-- already seeded from a richer source (e.g. scraper:marburg), so the existing
-- Marburg row -- with its faculty/degree_program/catalog_course tree already
-- attached -- never gets a duplicate sibling entry in the picker.
-- ============================================================================

INSERT INTO public.universities (name, country, email_domains, source, external_ref, last_scraped_at)
SELECT v.name, v.country, v.email_domains, 'hipo', v.external_ref, now()
FROM (VALUES
('Akademie der bildenden Künste Wien', 'Austria', ARRAY['akbild.ac.at']::TEXT[], 'akbild.ac.at'),
('Universität für Bodenkultur Wien', 'Austria', ARRAY['boku.ac.at']::TEXT[], 'boku.ac.at'),
('Donau-Universität Krems', 'Austria', ARRAY['donau-uni.ac.at']::TEXT[], 'donau-uni.ac.at'),
('Fachhochschule Burgenland', 'Austria', ARRAY['fh-burgenland.at']::TEXT[], 'fh-burgenland.at'),
('Fachhochschulstudiengänge Hagenberg', 'Austria', ARRAY['fh-hagenberg.at']::TEXT[], 'fh-hagenberg.at'),
('Fachhochschule JOANNEUM', 'Austria', ARRAY['fh-joanneum.at']::TEXT[], 'fh-joanneum.at'),
('Fachhochschule Kärnten', 'Austria', ARRAY['fh-kaernten.ac.at']::TEXT[], 'fh-kaernten.ac.at'),
('Fachhochschule Krems', 'Austria', ARRAY['fh-krems.ac.at']::TEXT[], 'fh-krems.ac.at'),
('Fachhochschule Kufstein (Tirol)', 'Austria', ARRAY['fh-kufstein.ac.at']::TEXT[], 'fh-kufstein.ac.at'),
('Fachhochschule Salzburg', 'Austria', ARRAY['fh-sbg.ac.at']::TEXT[], 'fh-sbg.ac.at'),
('Fachhochschulstudiengänge Steyr', 'Austria', ARRAY['fh-steyr.at']::TEXT[], 'fh-steyr.at'),
('Fachhochschule St. Pölten', 'Austria', ARRAY['fh-stpoelten.ac.at']::TEXT[], 'fh-stpoelten.ac.at'),
('Fachhochschule Vorarlberg', 'Austria', ARRAY['fhv.at']::TEXT[], 'fhv.at'),
('Fachhochschule für Bank- und Finanzwirtschaft', 'Austria', ARRAY['fh-vie.ac.at']::TEXT[], 'fh-vie.ac.at'),
('Fachhochschulstudiengänge der Wiener Wirtschaft', 'Austria', ARRAY['fhw.at']::TEXT[], 'fhw.at'),
('Fachhochschulstudiengänge Wels', 'Austria', ARRAY['fh-wels.at']::TEXT[], 'fh-wels.at'),
('Fachhochschule Wiener Neustadt', 'Austria', ARRAY['fhwn.ac.at']::TEXT[], 'fhwn.ac.at'),
('Fachhochschulstudiengänge Krems IMC', 'Austria', ARRAY['imc-krems.ac.at']::TEXT[], 'imc-krems.ac.at'),
('Medizinische Universität Innsbruck', 'Austria', ARRAY['i-med.ac.at']::TEXT[], 'i-med.ac.at'),
('Institute of Science and Technology', 'Austria', ARRAY['ist.ac.at']::TEXT[], 'ist.ac.at'),
('Universität Graz', 'Austria', ARRAY['kfunigraz.ac.at']::TEXT[], 'kfunigraz.ac.at'),
('Universität für künstlerische und industrielle Gestaltung Linz', 'Austria', ARRAY['khs-linz.ac.at']::TEXT[], 'khs-linz.ac.at'),
('Katholisch-Theologische Privatuniversität Linz', 'Austria', ARRAY['kth-linz.ac.at']::TEXT[], 'kth-linz.ac.at'),
('Universität für Musik und darstellende Kunst Graz', 'Austria', ARRAY['kug.ac.at']::TEXT[], 'kug.ac.at'),
('MCI-Management Center Innsbruck', 'Austria', ARRAY['mci.edu']::TEXT[], 'mci.edu'),
('Universität für Musik und darstellende Kunst Wien', 'Austria', ARRAY['mdw.ac.at']::TEXT[], 'mdw.ac.at'),
('Medizinische Universität Graz', 'Austria', ARRAY['meduni-graz.at']::TEXT[], 'meduni-graz.at'),
('Medizinische Universität Wien', 'Austria', ARRAY['meduniwien.at']::TEXT[], 'meduniwien.at'),
('Universität Mozarteum Salzburg', 'Austria', ARRAY['moz.ac.at']::TEXT[], 'moz.ac.at'),
('Universität für angewandte Kunst Wien', 'Austria', ARRAY['ns2.uni-ak.ac.at']::TEXT[], 'ns2.uni-ak.ac.at'),
('Universität Salzburg', 'Austria', ARRAY['sbg.ac.at']::TEXT[], 'sbg.ac.at'),
('Technikum Wien', 'Austria', ARRAY['technikum-wien.at']::TEXT[], 'technikum-wien.at'),
('Technische Universität Graz', 'Austria', ARRAY['tugraz.at']::TEXT[], 'tugraz.at'),
('Technische Universität Wien', 'Austria', ARRAY['tuwien.ac.at']::TEXT[], 'tuwien.ac.at'),
('Universität Innsbruck', 'Austria', ARRAY['uibk.ac.at']::TEXT[], 'uibk.ac.at'),
('Private Universität für Medizinische Informatik und Technik Tirol', 'Austria', ARRAY['umit.at']::TEXT[], 'umit.at'),
('Universität Klagenfurt', 'Austria', ARRAY['uni-klu.ac.at']::TEXT[], 'uni-klu.ac.at'),
('Montanuniversität Leoben', 'Austria', ARRAY['unileoben.ac.at']::TEXT[], 'unileoben.ac.at'),
('Johannes Kepler Universität Linz', 'Austria', ARRAY['jku.at']::TEXT[], 'jku.at'),
('Universität Vienna', 'Austria', ARRAY['univie.ac.at']::TEXT[], 'univie.ac.at'),
('Veterinärmedizinische Universität Wien', 'Austria', ARRAY['vu-wien.ac.at']::TEXT[], 'vu-wien.ac.at'),
('Webster University, Vienna', 'Austria', ARRAY['webster.ac.at']::TEXT[], 'webster.ac.at'),
('Wirtschaftsuniversität Wien', 'Austria', ARRAY['wu-wien.ac.at','wu.ac.at']::TEXT[], 'wu-wien.ac.at'),
('IU Internationale Hochschule GmbH', 'Germany', ARRAY['iubh-fernstudium.de']::TEXT[], 'iubh-fernstudium.de'),
('AKAD Hochschulen für Berufstätige, Fachhochschule Leipzig', 'Germany', ARRAY['akad.de']::TEXT[], 'akad.de'),
('Alice-Salomon-Fachhochschule für Sozialarbeit und Sozialpädagogik Berlin', 'Germany', ARRAY['asfh-berlin.de']::TEXT[], 'asfh-berlin.de'),
('Augustana Hochschule Neuendettelsau', 'Germany', ARRAY['augustana.de']::TEXT[], 'augustana.de'),
('Kirchliche Hochschule Bethel', 'Germany', ARRAY['bethel.de']::TEXT[], 'bethel.de'),
('BiTS - Business and Information Technology School gGmbH', 'Germany', ARRAY['bits-iserlohn.de']::TEXT[], 'bits-iserlohn.de'),
('Cologne Business School', 'Germany', ARRAY['cbs.de']::TEXT[], 'cbs.de'),
('Charité – Universitätsmedizin Berlin', 'Germany', ARRAY['charite.de']::TEXT[], 'charite.de'),
('CODE University of Applied Sciences Berlin', 'Germany', ARRAY['code.berlin']::TEXT[], 'code.berlin'),
('Deutsche Hochschule für Verwaltungswissenschaften Speyer', 'Germany', ARRAY['dhv-speyer.de']::TEXT[], 'dhv-speyer.de'),
('DIPLOMA-Fachhochschule Ölsnitz/Vogtland', 'Germany', ARRAY['diploma.de']::TEXT[], 'diploma.de'),
('Deutsche Sporthochschule Köln', 'Germany', ARRAY['dshs-koeln.de']::TEXT[], 'dshs-koeln.de'),
('E.A.P. Europäische Wirtschaftshochschule Berlin', 'Germany', ARRAY['eap.net']::TEXT[], 'eap.net'),
('Europäische Betriebswirtschafts-Akademie', 'Germany', ARRAY['eba-muenchen.de']::TEXT[], 'eba-muenchen.de'),
('European Business School Schloß Reichartshausen', 'Germany', ARRAY['ebs.de']::TEXT[], 'ebs.de'),
('European College of Liberal Arts', 'Germany', ARRAY['ecla.de']::TEXT[], 'ecla.de'),
('Evangelische Fachhochschule Rheinland-Westfalen-Lippe', 'Germany', ARRAY['efh-bochum.de']::TEXT[], 'efh-bochum.de'),
('Evangelische Fachhochschule Darmstadt', 'Germany', ARRAY['eh-darmstadt.de']::TEXT[], 'eh-darmstadt.de'),
('Evangelische Fachhochschule Freiburg, Hochschule für Soziale Arbeit, Diakonie und Religionspädagogik', 'Germany', ARRAY['efh-freiburg.de']::TEXT[], 'efh-freiburg.de'),
('Evangelische Fachhochschule Hannover', 'Germany', ARRAY['efh-hannover.de']::TEXT[], 'efh-hannover.de'),
('Evangelische Fachhochschule Ludwigshafen Hochschule für Sozial- und Gesundheitswesen', 'Germany', ARRAY['efhlu.de']::TEXT[], 'efhlu.de'),
('Evangelische Fachhochschule Reutlingen-Ludwigsburg, Hochschule für Soziale Arbeit, Religionspädagogik und Diakonie', 'Germany', ARRAY['efh-reutlingen-ludwigsburg.de']::TEXT[], 'efh-reutlingen-ludwigsburg.de'),
('Evangelische Hochschule für Soziale Arbeit Dresden (FH)', 'Germany', ARRAY['ehs-dresden.de']::TEXT[], 'ehs-dresden.de'),
('European Management School', 'Germany', ARRAY['ems-mainz.de']::TEXT[], 'ems-mainz.de'),
('Europäische Fachhochschule', 'Germany', ARRAY['eufh.de']::TEXT[], 'eufh.de'),
('Europa-Universität Viadrina Frankfurt (Oder)', 'Germany', ARRAY['euv-frankfurt-o.de']::TEXT[], 'euv-frankfurt-o.de'),
('Evangelische Fachhochschule Berlin, Fachhochschule für Sozialarbeit und Sozialpädagogik', 'Germany', ARRAY['evfh-berlin.de']::TEXT[], 'evfh-berlin.de'),
('Evangelische Fachhochschule Nürnberg', 'Germany', ARRAY['evfh-nuernberg.de']::TEXT[], 'evfh-nuernberg.de'),
('Fern-Fachhochschule Hamburg', 'Germany', ARRAY['fern-fh.de']::TEXT[], 'fern-fh.de'),
('Fernuniversität Gesamthochschule Hagen', 'Germany', ARRAY['fernuni-hagen.de']::TEXT[], 'fernuni-hagen.de'),
('Fachhochschule Aachen', 'Germany', ARRAY['fh-aachen.de']::TEXT[], 'fh-aachen.de'),
('Fachhochschule Aschaffenburg', 'Germany', ARRAY['fh-aschaffenburg.de']::TEXT[], 'fh-aschaffenburg.de'),
('Technical University of Applied Sciences Augsburg', 'Germany', ARRAY['fh-augsburg.de','tha.de']::TEXT[], 'fh-augsburg.de'),
('Internationale Fachhochschule Bad Honnef', 'Germany', ARRAY['fh-bad-honnef.de']::TEXT[], 'fh-bad-honnef.de'),
('Fachhochschule Biberach, Hochschule für Bauwesen und Wirtschaft', 'Germany', ARRAY['fh-biberach.de']::TEXT[], 'fh-biberach.de'),
('Fachhochschule Bielefeld', 'Germany', ARRAY['fh-bielefeld.de']::TEXT[], 'fh-bielefeld.de'),
('Fachhochschule Bingen', 'Germany', ARRAY['fh-bingen.de']::TEXT[], 'fh-bingen.de'),
('Fachhochschule Bochum', 'Germany', ARRAY['fh-bochum.de']::TEXT[], 'fh-bochum.de'),
('Hochschule Bonn-Rhein-Sieg', 'Germany', ARRAY['hochschule-bonn-rhein-sieg.de','h-brs.de']::TEXT[], 'hochschule-bonn-rhein-sieg.de'),
('Fachhochschule Brandenburg', 'Germany', ARRAY['fh-brandenburg.de']::TEXT[], 'fh-brandenburg.de'),
('Technische Hochschule Brandenburg', 'Germany', ARRAY['th-brandenburg.de']::TEXT[], 'th-brandenburg.de'),
('Technische Hochschule Deggendorf', 'Germany', ARRAY['th-deg.de']::TEXT[], 'th-deg.de'),
('Fachhochschule Dortmund', 'Germany', ARRAY['fh-dortmund.de']::TEXT[], 'fh-dortmund.de'),
('Hochschule Düsseldorf', 'Germany', ARRAY['hs-duesseldorf.de']::TEXT[], 'hs-duesseldorf.de'),
('Fachhochschule für die Wirtschaft', 'Germany', ARRAY['fhdw.bib.de']::TEXT[], 'fhdw.bib.de'),
('Fachhochschule der Wirtschaft', 'Germany', ARRAY['fhdw.de']::TEXT[], 'fhdw.de'),
('Fachhochschule Eberswalde', 'Germany', ARRAY['fh-eberswalde.de']::TEXT[], 'fh-eberswalde.de'),
('Fachhochschule Erfurt', 'Germany', ARRAY['fh-erfurt.de']::TEXT[], 'fh-erfurt.de'),
('Fachhochschule Flensburg', 'Germany', ARRAY['fh-flensburg.de']::TEXT[], 'fh-flensburg.de'),
('Fachhochschule Frankfurt am Main', 'Germany', ARRAY['fh-frankfurt.de']::TEXT[], 'fh-frankfurt.de'),
('Europa Fachhochschule Fresenius', 'Germany', ARRAY['fh-fresenius.de']::TEXT[], 'fh-fresenius.de'),
('Fachhochschule Furtwangen, Hochschule für Technik und Wirtschaft', 'Germany', ARRAY['fh-furtwangen.de']::TEXT[], 'fh-furtwangen.de'),
('Fachhochschule Gelsenkirchen', 'Germany', ARRAY['fh-gelsenkirchen.de']::TEXT[], 'fh-gelsenkirchen.de'),
('Fachhochschule Gießen-Friedberg', 'Germany', ARRAY['fh-giessen.de']::TEXT[], 'fh-giessen.de'),
('Fachhochschule Hamburg', 'Germany', ARRAY['fh-hamburg.de']::TEXT[], 'fh-hamburg.de'),
('Hamburg University of Applied Sciences (HAW Hamburg)', 'Germany', ARRAY['haw-hamburg.de']::TEXT[], 'haw-hamburg.de'),
('Fachhochschule Hannover', 'Germany', ARRAY['fh-hannover.de']::TEXT[], 'fh-hannover.de'),
('Fachhochschule Heidelberg', 'Germany', ARRAY['fh-heidelberg.de']::TEXT[], 'fh-heidelberg.de'),
('Fachhochschule Heilbronn, Hochschule für Technik und Wirtschaft', 'Germany', ARRAY['fh-heilbronn.de']::TEXT[], 'fh-heilbronn.de'),
('Fachhochschule Hildesheim/Holzminden/Göttingen, Hochschule für angewandte Wissenschaft und Kunst', 'Germany', ARRAY['fh-hildesheim.de']::TEXT[], 'fh-hildesheim.de'),
('Fachhochschule Hof', 'Germany', ARRAY['fh-hof.de']::TEXT[], 'fh-hof.de'),
('Technische Hochschule Ingolstadt', 'Germany', ARRAY['thi.de']::TEXT[], 'thi.de'),
('Fachhochschule und Berufskollegs NTA, Prof.Dr. Grübler gemein. GmbH', 'Germany', ARRAY['fh-isny.de']::TEXT[], 'fh-isny.de'),
('Fachhochschule Jena', 'Germany', ARRAY['fh-jena.de']::TEXT[], 'fh-jena.de'),
('Fachhochschule Karlsruhe, Hochschule für Technik', 'Germany', ARRAY['fh-karlsruhe.de']::TEXT[], 'fh-karlsruhe.de'),
('Fachhochschule Kempten, Hochschule für Technik und Wirtschaft', 'Germany', ARRAY['fh-kempten.de']::TEXT[], 'fh-kempten.de'),
('Fachhochschule Kiel', 'Germany', ARRAY['fh-kiel.de']::TEXT[], 'fh-kiel.de'),
('Fachhochschule Kaiserslautern', 'Germany', ARRAY['fh-kl.de']::TEXT[], 'fh-kl.de'),
('Fachhochschule Koblenz', 'Germany', ARRAY['fh-koblenz.de']::TEXT[], 'fh-koblenz.de'),
('Technische Hochschule Köln', 'Germany', ARRAY['th-koeln.de','fh-koeln.de']::TEXT[], 'th-koeln.de'),
('Fachhochschule Konstanz, Hochschule für Technik, Wirtschaft und Gestaltung', 'Germany', ARRAY['fh-konstanz.de']::TEXT[], 'fh-konstanz.de'),
('Staatlich anerkannte Fachhochschule für Kunsttherapie', 'Germany', ARRAY['fhkt.de']::TEXT[], 'fhkt.de'),
('Fachhochschule Landshut, Hochschule für Wirtschaft - Sozialwesen - Technik', 'Germany', ARRAY['fh-landshut.de']::TEXT[], 'fh-landshut.de'),
('Fachhochschule Lausitz', 'Germany', ARRAY['fh-lausitz.de']::TEXT[], 'fh-lausitz.de'),
('Fachhochschule Lippe', 'Germany', ARRAY['fh-lippe.de']::TEXT[], 'fh-lippe.de'),
('Fachhochschule Ludwigshafen, Hochschule für Wirtschaft', 'Germany', ARRAY['fh-ludwigshafen.de']::TEXT[], 'fh-ludwigshafen.de'),
('Fachhochschule Lübeck', 'Germany', ARRAY['fh-luebeck.de']::TEXT[], 'fh-luebeck.de'),
('Fachhochschule Mainz', 'Germany', ARRAY['fh-mainz.de']::TEXT[], 'fh-mainz.de'),
('Fachhochschule Mannheim, Hochschule für Technik und Gestaltung', 'Germany', ARRAY['fh-mannheim.de']::TEXT[], 'fh-mannheim.de'),
('Fachhochschule Merseburg', 'Germany', ARRAY['fh-merseburg.de']::TEXT[], 'fh-merseburg.de'),
('Fachhochschule des Mittelstandes (FHM)', 'Germany', ARRAY['fhm-mittelstand.de']::TEXT[], 'fhm-mittelstand.de'),
('Fachhochschule München', 'Germany', ARRAY['fh-muenchen.de']::TEXT[], 'fh-muenchen.de'),
('Hochschule München', 'Germany', ARRAY['hm.edu']::TEXT[], 'hm.edu'),
('Fachhochschule Münster', 'Germany', ARRAY['fh-muenster.de']::TEXT[], 'fh-muenster.de'),
('Fachhochschule Neubrandenburg', 'Germany', ARRAY['fh-nb.de']::TEXT[], 'fh-nb.de'),
('Hochschule Neu-Ulm, Hochschule Neu-Ulm University of applied sciences', 'Germany', ARRAY['hs-neu-ulm.de']::TEXT[], 'hs-neu-ulm.de'),
('Fachhochschule Niederrhein', 'Germany', ARRAY['fh-niederrhein.de']::TEXT[], 'fh-niederrhein.de'),
('Fachhochschule Nordostniedersachsen', 'Germany', ARRAY['fhnon.de']::TEXT[], 'fhnon.de'),
('Fachhochschule Nordhausen', 'Germany', ARRAY['fh-nordhausen.de']::TEXT[], 'fh-nordhausen.de'),
('Georg-Simon-Ohm-Fachhochschule Nürnberg', 'Germany', ARRAY['fh-nuernberg.de']::TEXT[], 'fh-nuernberg.de'),
('Fachhochschule Nürtingen, Hochschule für Wirtschaft, Landwirtschaft und Landespflege', 'Germany', ARRAY['fh-nuertingen.de']::TEXT[], 'fh-nuertingen.de'),
('Fachhochschule für das öffentliche Bibliothekswesen Bonn', 'Germany', ARRAY['fhoebb.de']::TEXT[], 'fhoebb.de'),
('Fachhochschule Offenburg, Hochschule für Technik und Wirtschaft', 'Germany', ARRAY['fh-offenburg.de']::TEXT[], 'fh-offenburg.de'),
('Fachhochschule Oldenburg/Ostfriesland/Wilhelmshaven', 'Germany', ARRAY['fh-oow.de']::TEXT[], 'fh-oow.de'),
('Fachhochschule Osnabrück', 'Germany', ARRAY['fh-osnabrueck.de']::TEXT[], 'fh-osnabrueck.de'),
('Freie Kunst-Studienstätte Ottersberg', 'Germany', ARRAY['fh-ottersberg.de']::TEXT[], 'fh-ottersberg.de'),
('Fachhochschule Pforzheim, Hochschule für Gestaltung, Technik und Wirtschaft', 'Germany', ARRAY['fh-pforzheim.de']::TEXT[], 'fh-pforzheim.de'),
('Fachhochschule Potsdam', 'Germany', ARRAY['fh-potsdam.de']::TEXT[], 'fh-potsdam.de'),
('Fachhochschule Regensburg', 'Germany', ARRAY['fh-regensburg.de']::TEXT[], 'fh-regensburg.de'),
('Fachhochschule Reutlingen, Hochschule für Technik und Wirtschaft', 'Germany', ARRAY['fh-reutlingen.de']::TEXT[], 'fh-reutlingen.de'),
('Deutsch-Ordens Fachhochschule Riedlingen, Hochschule für Wirtschaft', 'Germany', ARRAY['fh-riedlingen.de']::TEXT[], 'fh-riedlingen.de'),
('Fachhochschule Rosenheim, Hochschule für Technik und Wirtschaft', 'Germany', ARRAY['fh-rosenheim.de']::TEXT[], 'fh-rosenheim.de'),
('Fachhochschule Rottenburg, Hochschule für Forstwirtschaft', 'Germany', ARRAY['fh-rottenburg.de']::TEXT[], 'fh-rottenburg.de'),
('Fachhochschule Schmalkalden', 'Germany', ARRAY['fh-schmalkalden.de']::TEXT[], 'fh-schmalkalden.de'),
('Fachhochschule Schwäbisch Hall, Hochschule für Gestaltung', 'Germany', ARRAY['fh-schwaebischhall.de']::TEXT[], 'fh-schwaebischhall.de'),
('Fachhochschule Mannheim, Hochschule für Sozialwesen', 'Germany', ARRAY['fhs-mannheim.de']::TEXT[], 'fhs-mannheim.de'),
('Evangelische Fachhochschule für Religionspädagogik, und Gemeindediakonie Moritzburg', 'Germany', ARRAY['fhs-moritzburg.de']::TEXT[], 'fhs-moritzburg.de'),
('Fachhochschule Stralsund', 'Germany', ARRAY['fh-stralsund.de']::TEXT[], 'fh-stralsund.de'),
('Deutsche Telekom Fachhochschule Leipzig', 'Germany', ARRAY['fh-telekom-leipzig.de']::TEXT[], 'fh-telekom-leipzig.de'),
('Fachhochschule Trier, Hochschule für Technik, Wirtschaft und Gestaltung', 'Germany', ARRAY['fh-trier.de']::TEXT[], 'fh-trier.de'),
('Fachhochschule Stuttgart, Hochschule für Technik', 'Germany', ARRAY['fht-stuttgart.de']::TEXT[], 'fht-stuttgart.de'),
('Hochschule für Technik und Wirtschaft Berlin', 'Germany', ARRAY['fhtw-berlin.de','htw-berlin.de']::TEXT[], 'fhtw-berlin.de'),
('Hochschule Ulm, Hochschule für Angewandte Wissenschaft', 'Germany', ARRAY['hs-ulm.de']::TEXT[], 'hs-ulm.de'),
('Fachhochschule für Verwaltung und Rechtspflege Berlin', 'Germany', ARRAY['fhvr.berlin.de']::TEXT[], 'fhvr.berlin.de'),
('Fachhochschule für Wirtschaft Berlin', 'Germany', ARRAY['fhw-berlin.de']::TEXT[], 'fhw-berlin.de'),
('Fachhochschule Wedel', 'Germany', ARRAY['fh-wedel.de']::TEXT[], 'fh-wedel.de'),
('Fachhochschule Weihenstephan', 'Germany', ARRAY['fh-weihenstephan.de']::TEXT[], 'fh-weihenstephan.de'),
('Fachhochschule Ravensburg-Weingarten', 'Germany', ARRAY['fh-weingarten.de']::TEXT[], 'fh-weingarten.de'),
('Fachhochschule Westküste, Hochschule für Wirtschaft und Technik', 'Germany', ARRAY['fh-westkueste.de']::TEXT[], 'fh-westkueste.de'),
('Fachhochschule Wiesbaden', 'Germany', ARRAY['fh-wiesbaden.de']::TEXT[], 'fh-wiesbaden.de'),
('Ostfalia Hochschule für angewandte Wissenschaften', 'Germany', ARRAY['ostfalia.de','fh-wolfenbuettel.de']::TEXT[], 'ostfalia.de'),
('Fachhochschule Worms', 'Germany', ARRAY['fh-worms.de']::TEXT[], 'fh-worms.de'),
('Private Fachhochschule für Wirtschaft und Technik Vechta/Diepholz', 'Germany', ARRAY['fhwt.de']::TEXT[], 'fhwt.de'),
('Fachhochschule Würzburg - Schweinfurt', 'Germany', ARRAY['fh-wuerzburg.de']::TEXT[], 'fh-wuerzburg.de'),
('Westsächsische Hochschule Zwickau (FH)', 'Germany', ARRAY['fh-zwickau.de']::TEXT[], 'fh-zwickau.de'),
('Fachhochschule für Oekonomie und Management (FOM)', 'Germany', ARRAY['fom.de']::TEXT[], 'fom.de'),
('Freie Universität Berlin', 'Germany', ARRAY['fu-berlin.de']::TEXT[], 'fu-berlin.de'),
('Private Hanseuniversität', 'Germany', ARRAY['hanseuni.de']::TEXT[], 'hanseuni.de'),
('Hafencity Universität Hamburg', 'Germany', ARRAY['hcu-hamburg.de']::TEXT[], 'hcu-hamburg.de'),
('Fachhochschule Stuttgart, Hochschule der Medien', 'Germany', ARRAY['hdm-stuttgart.de']::TEXT[], 'hdm-stuttgart.de'),
('Hertie School of Governance', 'Germany', ARRAY['hertie-school.org']::TEXT[], 'hertie-school.org'),
('Hochschule für Bankwirtschaft (HfB), Private Fachhochschule der Bankakademie', 'Germany', ARRAY['hfb.de']::TEXT[], 'hfb.de'),
('Fachhochschule Schwäbisch Gmünd, Hochschule für Gestaltung', 'Germany', ARRAY['hfg-gmuend.de']::TEXT[], 'hfg-gmuend.de'),
('Hochschule für Philosophie München', 'Germany', ARRAY['hfph.mwn.de']::TEXT[], 'hfph.mwn.de'),
('Hochschule für Politik (HFP)', 'Germany', ARRAY['hfp.mhn.de']::TEXT[], 'hfp.mhn.de'),
('Handelshochschule Leipzig', 'Germany', ARRAY['hhl.de']::TEXT[], 'hhl.de'),
('Hochschule für Internationales Management', 'Germany', ARRAY['himh.de']::TEXT[], 'himh.de'),
('Hochschule für Jüdische Studien Heidelberg', 'Germany', ARRAY['hjs.uni-heidelberg.de']::TEXT[], 'hjs.uni-heidelberg.de'),
('Hochschule Albstadt-Sigmaringen', 'Germany', ARRAY['hs-albsig.de']::TEXT[], 'hs-albsig.de'),
('Hochschule Anhalt (FH), Hochschule für angewandte Wissenschaften', 'Germany', ARRAY['hs-anhalt.de','student.hs-anhalt.de']::TEXT[], 'hs-anhalt.de'),
('Hochschule Bremen', 'Germany', ARRAY['hs-bremen.de']::TEXT[], 'hs-bremen.de'),
('Hochschule Bremerhaven', 'Germany', ARRAY['hs-bremerhaven.de']::TEXT[], 'hs-bremerhaven.de'),
('Hochschule Coburg', 'Germany', ARRAY['hs-coburg.de']::TEXT[], 'hs-coburg.de'),
('Hochschule Darmstadt', 'Germany', ARRAY['h-da.de']::TEXT[], 'h-da.de'),
('Hochschule Esslingen', 'Germany', ARRAY['hs-esslingen.de']::TEXT[], 'hs-esslingen.de'),
('Hochschule Fulda', 'Germany', ARRAY['hs-fulda.de']::TEXT[], 'hs-fulda.de'),
('Hochschule Harz, Hochschule für angewandte Wissenschaften (FH)', 'Germany', ARRAY['hs-harz.de']::TEXT[], 'hs-harz.de'),
('Hochschule Magdeburg-Stendal (FH)', 'Germany', ARRAY['hs-magdeburg.de']::TEXT[], 'hs-magdeburg.de'),
('Hochschule Wismar, Fachhochschule für Technik, Wirtschaft und Gestaltung', 'Germany', ARRAY['hs-wismar.de']::TEXT[], 'hs-wismar.de'),
('Hochschule Zittau/Görlitz (FH)', 'Germany', ARRAY['hs-zigr.de']::TEXT[], 'hs-zigr.de'),
('Hochschule für Technik und Wirtschaft Dresden (FH)', 'Germany', ARRAY['htw-dresden.de']::TEXT[], 'htw-dresden.de'),
('Hochschule für Technik, Wirtschaft und Kultur Leipzig (FH)', 'Germany', ARRAY['htwk-leipzig.de']::TEXT[], 'htwk-leipzig.de'),
('Hochschule Mittweida, University of Applied Sciences', 'Germany', ARRAY['htwm.de','hs-mittweida.de','campus-m-university.de','campusm21.de']::TEXT[], 'htwm.de'),
('Hochschule für Technik und Wirtschaft des Saarlandes', 'Germany', ARRAY['htw-saarland.de']::TEXT[], 'htw-saarland.de'),
('Humboldt Universität Berlin', 'Germany', ARRAY['hu-berlin.de']::TEXT[], 'hu-berlin.de'),
('HWP - Hamburger Universität für Wirtschaft und Politik', 'Germany', ARRAY['hwp-hamburg.de']::TEXT[], 'hwp-hamburg.de'),
('Internationales Hochschulinstitut Zittau', 'Germany', ARRAY['ihi-zittau.de']::TEXT[], 'ihi-zittau.de'),
('Internationale Fachhochschule Aalen', 'Germany', ARRAY['international.fh-aalen.de']::TEXT[], 'international.fh-aalen.de'),
('International School of Management ISM Dortmund', 'Germany', ARRAY['ism-dortmund.de']::TEXT[], 'ism-dortmund.de'),
('International School of New Media, University of Lübeck', 'Germany', ARRAY['isnm.de']::TEXT[], 'isnm.de'),
('International University in Germany', 'Germany', ARRAY['i-u.de']::TEXT[], 'i-u.de'),
('Jacobs University Bremen', 'Germany', ARRAY['jacobs-university.de']::TEXT[], 'jacobs-university.de'),
('Karlshochschule International University', 'Germany', ARRAY['karlshochschule.de']::TEXT[], 'karlshochschule.de'),
('Katholische Fachhochschule Norddeutschland', 'Germany', ARRAY['kath-fh-nord.de']::TEXT[], 'kath-fh-nord.de'),
('Katholische Fachhochschule Berlin (KFB)', 'Germany', ARRAY['kfb-berlin.de']::TEXT[], 'kfb-berlin.de'),
('Katholische Fachhochschule Freiburg, Hochschule für Sozialwesen, Religionspädagogik und Pflege', 'Germany', ARRAY['kfh-freiburg.de']::TEXT[], 'kfh-freiburg.de'),
('Katholische Fachhochschule Mainz', 'Germany', ARRAY['kfh-mainz.de']::TEXT[], 'kfh-mainz.de'),
('Katholische Fachhochschule Nordrhein-Westfalen', 'Germany', ARRAY['kfhnw.de']::TEXT[], 'kfhnw.de'),
('Kunsthochschule Berlin-Weissensee, Hochschule für Gestaltung', 'Germany', ARRAY['kh-berlin.de']::TEXT[], 'kh-berlin.de'),
('Katholische Hochschule für Soziale Arbeit Saarbrücken', 'Germany', ARRAY['khsa.de']::TEXT[], 'khsa.de'),
('Katholische Stiftungsfachhochschule München', 'Germany', ARRAY['ksfh.de']::TEXT[], 'ksfh.de'),
('Katholische Universität Eichstätt', 'Germany', ARRAY['ku-eichstaett.de']::TEXT[], 'ku-eichstaett.de'),
('Kunstakademie Düsseldorf.', 'Germany', ARRAY['kunstakademie-duesseldorf.de']::TEXT[], 'kunstakademie-duesseldorf.de'),
('Merkur Internationale FH Karlsruhe', 'Germany', ARRAY['merkur-fh.org']::TEXT[], 'merkur-fh.org'),
('Merz Akademie, Hochschule für Gestaltung Stuttgart', 'Germany', ARRAY['merz-akademie.de']::TEXT[], 'merz-akademie.de'),
('Märkische Fachhochschule Iserlohn', 'Germany', ARRAY['mfh-iserlohn.de']::TEXT[], 'mfh-iserlohn.de'),
('Medizinische Hochschule Hannover', 'Germany', ARRAY['mh-hannover.de']::TEXT[], 'mh-hannover.de'),
('Staatliche Hochschule für Musik', 'Germany', ARRAY['mh-trossingen.de']::TEXT[], 'mh-trossingen.de'),
('Medizinische Universität Lübeck', 'Germany', ARRAY['mu-luebeck.de']::TEXT[], 'mu-luebeck.de'),
('Muthesius-Hochschule, Fachhochschule für Kunst und Gestaltung', 'Germany', ARRAY['muthesius.de']::TEXT[], 'muthesius.de'),
('Nordakademie, Staatlich anerkannte private Fachhochschule mit dualen Studiengängen', 'Germany', ARRAY['nordakademie.de']::TEXT[], 'nordakademie.de'),
('Theologische Fakultät Paderborn', 'Germany', ARRAY['paderborn.de']::TEXT[], 'paderborn.de'),
('Private Fachhochschule Göttingen', 'Germany', ARRAY['pfh-goettingen.de']::TEXT[], 'pfh-goettingen.de'),
('Pädagogische Hochschule Erfurt/Mühlhausen', 'Germany', ARRAY['ph-erfurt.de']::TEXT[], 'ph-erfurt.de'),
('Pädagogische Hochschule Freiburg', 'Germany', ARRAY['ph-freiburg.de']::TEXT[], 'ph-freiburg.de'),
('Pädagogische Hochschule Schwäbisch Gmünd', 'Germany', ARRAY['ph-gmuend.de']::TEXT[], 'ph-gmuend.de'),
('Pädagogische Hochschule Heidelberg', 'Germany', ARRAY['ph-heidelberg.de']::TEXT[], 'ph-heidelberg.de'),
('Philosophisch-Theologische Hochschule SVD Sankt Augustin', 'Germany', ARRAY['philtheol-augustin.de']::TEXT[], 'philtheol-augustin.de'),
('Pädagogische Hochschule Karlsruhe', 'Germany', ARRAY['ph-karlsruhe.de']::TEXT[], 'ph-karlsruhe.de'),
('Pädagogische Hochschule Ludwigsburg', 'Germany', ARRAY['ph-ludwigsburg.de']::TEXT[], 'ph-ludwigsburg.de'),
('Pädagogische Hochschule Weingarten', 'Germany', ARRAY['ph-weingarten.de']::TEXT[], 'ph-weingarten.de'),
('Popakademie Baden-Württemberg', 'Germany', ARRAY['popakademie.de']::TEXT[], 'popakademie.de'),
('Private FernFachhochschule Darmstadt', 'Germany', ARRAY['privatfh-da.de']::TEXT[], 'privatfh-da.de'),
('Philosophisch-Theologische Hochschule der Salesianer Don Boscos', 'Germany', ARRAY['pth-bb.de']::TEXT[], 'pth-bb.de'),
('Philosophisch-Theologische Hochschule Münster', 'Germany', ARRAY['pth-muenster.de']::TEXT[], 'pth-muenster.de'),
('Philosophisch-Theologische Hochschule Vallendar der Gesellschaft des Katholischen Apostolates (Pallottiner)', 'Germany', ARRAY['pthv.de']::TEXT[], 'pthv.de'),
('Evangelische Fachhochschule für Sozialpädagogik der "Diakonenanstalt des Rauhen Hauses" Hamburg', 'Germany', ARRAY['rauheshaus.de']::TEXT[], 'rauheshaus.de'),
('Rheinische Fachhochschule Köln', 'Germany', ARRAY['rfh-koeln.de']::TEXT[], 'rfh-koeln.de'),
('Ruhr-Universität Bochum', 'Germany', ARRAY['ruhr-uni-bochum.de']::TEXT[], 'ruhr-uni-bochum.de'),
('Rheinisch Westfälische Technische Hochschule Aachen', 'Germany', ARRAY['rwth-aachen.de']::TEXT[], 'rwth-aachen.de'),
('Lutherische Theologische Hochschule Oberursel', 'Germany', ARRAY['selk.de']::TEXT[], 'selk.de'),
('Gustav-Siewerth-Akademie', 'Germany', ARRAY['siewerth-akademie.de']::TEXT[], 'siewerth-akademie.de'),
('Schiller International University, Heidelberg', 'Germany', ARRAY['siu-heidelberg.de']::TEXT[], 'siu-heidelberg.de'),
('SRH University of Applied Sciences', 'Germany', ARRAY['srh-berlin.de']::TEXT[], 'srh-berlin.de'),
('Philosophisch-Theologische Hochschule Sankt Georgen', 'Germany', ARRAY['st-georgen.uni-frankfurt.de']::TEXT[], 'st-georgen.uni-frankfurt.de'),
('Steinbeis-Hochschule-Berlin', 'Germany', ARRAY['stw.de']::TEXT[], 'stw.de'),
('Technische Fachhochschule Berlin', 'Germany', ARRAY['tfh-berlin.de']::TEXT[], 'tfh-berlin.de'),
('Technische Fachhochschule Georg Agricola für Rohstoff, Energie und, Umwelt zu Bochum', 'Germany', ARRAY['tfh-bochum.de']::TEXT[], 'tfh-bochum.de'),
('Technische Fachhochschule Wildau', 'Germany', ARRAY['tfh-wildau.de']::TEXT[], 'tfh-wildau.de'),
('Theologische Hochschule Friedensau', 'Germany', ARRAY['thh-friedensau.de']::TEXT[], 'thh-friedensau.de'),
('Tierärztliche Hochschule Hannover', 'Germany', ARRAY['tiho-hannover.de']::TEXT[], 'tiho-hannover.de'),
('Technische Universität Berlin', 'Germany', ARRAY['tu-berlin.de']::TEXT[], 'tu-berlin.de'),
('Technische Universität Carolo-Wilhelmina zu Braunschweig', 'Germany', ARRAY['tu-braunschweig.de','tu-bs.de']::TEXT[], 'tu-braunschweig.de'),
('Technische Universität Chemnitz', 'Germany', ARRAY['tu-chemnitz.de']::TEXT[], 'tu-chemnitz.de'),
('Technische Universität Clausthal', 'Germany', ARRAY['tu-clausthal.de']::TEXT[], 'tu-clausthal.de'),
('Brandenburgische Technische Universität Cottbus', 'Germany', ARRAY['tu-cottbus.de']::TEXT[], 'tu-cottbus.de'),
('Technische Universität Darmstadt', 'Germany', ARRAY['tu-darmstadt.de']::TEXT[], 'tu-darmstadt.de'),
('Technische Universität Dresden', 'Germany', ARRAY['tu-dresden.de']::TEXT[], 'tu-dresden.de'),
('Technische Universität Bergakademie Freiberg', 'Germany', ARRAY['tu-freiberg.de']::TEXT[], 'tu-freiberg.de'),
('Technische Universität Hamburg', 'Germany', ARRAY['tuhh.de']::TEXT[], 'tuhh.de'),
('Technische Universität Ilmenau', 'Germany', ARRAY['tu-ilmenau.de']::TEXT[], 'tu-ilmenau.de'),
('Technische Universität München', 'Germany', ARRAY['tum.de','tum.edu','mytum.de']::TEXT[], 'tum.de'),
('Universität Augsburg', 'Germany', ARRAY['uni-augsburg.de']::TEXT[], 'uni-augsburg.de'),
('Otto-Friedrich Universität Bamberg', 'Germany', ARRAY['uni-bamberg.de']::TEXT[], 'uni-bamberg.de'),
('Universität Bayreuth', 'Germany', ARRAY['uni-bayreuth.de']::TEXT[], 'uni-bayreuth.de'),
('Universität Bielefeld', 'Germany', ARRAY['uni-bielefeld.de']::TEXT[], 'uni-bielefeld.de'),
('Rheinische Friedrich-Wilhelms Universität Bonn', 'Germany', ARRAY['uni-bonn.de']::TEXT[], 'uni-bonn.de'),
('Universität Bremen', 'Germany', ARRAY['uni-bremen.de']::TEXT[], 'uni-bremen.de'),
('Universität der Bundeswehr Hamburg', 'Germany', ARRAY['unibw-hamburg.de']::TEXT[], 'unibw-hamburg.de'),
('Universität der Bundeswehr München', 'Germany', ARRAY['unibw-muenchen.de']::TEXT[], 'unibw-muenchen.de'),
('Technische Universität Dortmund', 'Germany', ARRAY['tu-dortmund.de','udo.edu']::TEXT[], 'tu-dortmund.de'),
('Heinrich-Heine Universität Düsseldorf', 'Germany', ARRAY['uni-duesseldorf.de','hhu.de']::TEXT[], 'uni-duesseldorf.de'),
('Universität Duisburg-Essen', 'Germany', ARRAY['uni-duisburg-essen.de']::TEXT[], 'uni-duisburg-essen.de'),
('Universität Erfurt', 'Germany', ARRAY['uni-erfurt.de']::TEXT[], 'uni-erfurt.de'),
('Friedrich-Alexander Universität Erlangen-Nürnberg', 'Germany', ARRAY['fau.de','uni-erlangen.de']::TEXT[], 'fau.de'),
('Universität Flensburg', 'Germany', ARRAY['uni-flensburg.de']::TEXT[], 'uni-flensburg.de'),
('Johann Wolfgang Goethe Universität Frankfurt am Main', 'Germany', ARRAY['uni-frankfurt.de']::TEXT[], 'uni-frankfurt.de'),
('Albert-Ludwigs-Universität Freiburg', 'Germany', ARRAY['uni-freiburg.de']::TEXT[], 'uni-freiburg.de'),
('Justus Liebig Universität Gießen', 'Germany', ARRAY['uni-giessen.de']::TEXT[], 'uni-giessen.de'),
('Georg-August Universität Göttingen', 'Germany', ARRAY['uni-goettingen.de']::TEXT[], 'uni-goettingen.de'),
('Ernst-Moritz-Arndt Universität Greifswald', 'Germany', ARRAY['uni-greifswald.de']::TEXT[], 'uni-greifswald.de'),
('Martin-Luther Universität Halle-Wittenberg', 'Germany', ARRAY['uni-halle.de']::TEXT[], 'uni-halle.de'),
('Universität Hamburg', 'Germany', ARRAY['uni-hamburg.de']::TEXT[], 'uni-hamburg.de'),
('Universität Hannover', 'Germany', ARRAY['uni-hannover.de']::TEXT[], 'uni-hannover.de'),
('Ruprecht-Karls-Universität Heidelberg', 'Germany', ARRAY['uni-heidelberg.de']::TEXT[], 'uni-heidelberg.de'),
('Universität Hildesheim', 'Germany', ARRAY['uni-hildesheim.de']::TEXT[], 'uni-hildesheim.de'),
('Universität Hohenheim', 'Germany', ARRAY['uni-hohenheim.de']::TEXT[], 'uni-hohenheim.de'),
('Friedrich-Schiller Universität Jena', 'Germany', ARRAY['uni-jena.de']::TEXT[], 'uni-jena.de'),
('Karlsruher Institut für Technologie', 'Germany', ARRAY['kit.edu']::TEXT[], 'kit.edu'),
('Universität Kassel', 'Germany', ARRAY['uni-kassel.de']::TEXT[], 'uni-kassel.de'),
('Christian-Albrechts-Universität Kiel', 'Germany', ARRAY['uni-kiel.de']::TEXT[], 'uni-kiel.de'),
('Universität Kaiserslautern', 'Germany', ARRAY['uni-kl.de']::TEXT[], 'uni-kl.de'),
('Universität Koblenz-Landau', 'Germany', ARRAY['uni-koblenz-landau.de']::TEXT[], 'uni-koblenz-landau.de'),
('Universität Köln', 'Germany', ARRAY['uni-koeln.de']::TEXT[], 'uni-koeln.de'),
('Universität Konstanz', 'Germany', ARRAY['uni-konstanz.de']::TEXT[], 'uni-konstanz.de'),
('Universität Leipzig', 'Germany', ARRAY['uni-leipzig.de']::TEXT[], 'uni-leipzig.de'),
('Universität Lüneburg', 'Germany', ARRAY['uni-lueneburg.de']::TEXT[], 'uni-lueneburg.de'),
('Otto-von-Guericke Universität Magdeburg', 'Germany', ARRAY['uni-magdeburg.de']::TEXT[], 'uni-magdeburg.de'),
('Johannes-Gutenberg Universität Mainz', 'Germany', ARRAY['uni-mainz.de']::TEXT[], 'uni-mainz.de'),
('Universität Mannheim', 'Germany', ARRAY['uni-mannheim.de']::TEXT[], 'uni-mannheim.de'),
('Phillips-Universität Marburg', 'Germany', ARRAY['uni-marburg.de']::TEXT[], 'uni-marburg.de'),
('Ludwig-Maximilians-Universität München', 'Germany', ARRAY['lmu.de','uni-muenchen.de']::TEXT[], 'lmu.de'),
('Westfälische Wilhelms-Universität Münster', 'Germany', ARRAY['uni-muenster.de','wwu.de']::TEXT[], 'uni-muenster.de'),
('Carl von Ossietzky Universität Oldenburg', 'Germany', ARRAY['uol.de','uni-oldenburg.de']::TEXT[], 'uol.de'),
('Universität Osnabrück', 'Germany', ARRAY['uni-osnabrueck.de']::TEXT[], 'uni-osnabrueck.de'),
('Universität Paderborn', 'Germany', ARRAY['uni-paderborn.de']::TEXT[], 'uni-paderborn.de'),
('Universität Passau', 'Germany', ARRAY['uni-passau.de']::TEXT[], 'uni-passau.de'),
('Universität Potsdam', 'Germany', ARRAY['uni-potsdam.de']::TEXT[], 'uni-potsdam.de'),
('Universität Regensburg', 'Germany', ARRAY['uni-regensburg.de']::TEXT[], 'uni-regensburg.de'),
('Universität Rostock', 'Germany', ARRAY['uni-rostock.de']::TEXT[], 'uni-rostock.de'),
('Universität des Saarlandes', 'Germany', ARRAY['uni-saarland.de']::TEXT[], 'uni-saarland.de'),
('Universität Siegen', 'Germany', ARRAY['uni-siegen.de']::TEXT[], 'uni-siegen.de'),
('Universität Stuttgart', 'Germany', ARRAY['uni-stuttgart.de']::TEXT[], 'uni-stuttgart.de'),
('Universität Trier', 'Germany', ARRAY['uni-trier.de']::TEXT[], 'uni-trier.de'),
('Eberhard-Karls-Universität Tübingen', 'Germany', ARRAY['uni-tuebingen.de']::TEXT[], 'uni-tuebingen.de'),
('Universität Ulm', 'Germany', ARRAY['uni-ulm.de']::TEXT[], 'uni-ulm.de'),
('Hochschule Vechta', 'Germany', ARRAY['uni-vechta.de']::TEXT[], 'uni-vechta.de'),
('Bauhaus Universität Weimar', 'Germany', ARRAY['uni-weimar.de']::TEXT[], 'uni-weimar.de'),
('Private Universität Witten/Herdecke', 'Germany', ARRAY['uni-wh.de']::TEXT[], 'uni-wh.de'),
('Bayerische Julius-Maximilians-Universität Würzburg', 'Germany', ARRAY['uni-wuerzburg.de']::TEXT[], 'uni-wuerzburg.de'),
('Bergische Universität Gesamthochschule Wuppertal', 'Germany', ARRAY['uni-wuppertal.de']::TEXT[], 'uni-wuppertal.de'),
('WHU – Otto Beisheim School of Management', 'Germany', ARRAY['whu-koblenz.de','whu.edu']::TEXT[], 'whu-koblenz.de'),
('Schiller International University, American College of Switzerland', 'Switzerland', ARRAY['american-college.com']::TEXT[], 'american-college.com'),
('Business and Hotel Management School', 'Switzerland', ARRAY['bhms.ch']::TEXT[], 'bhms.ch'),
('Business School Lausanne (BSL)', 'Switzerland', ARRAY['bsl-lausanne.ch']::TEXT[], 'bsl-lausanne.ch'),
('Cubidor University Switzerland', 'Switzerland', ARRAY['cubidor.com']::TEXT[], 'cubidor.com'),
('DCT International Hotel & Business Management School', 'Switzerland', ARRAY['dct.ch']::TEXT[], 'dct.ch'),
('European Graduate School, Media & Communications', 'Switzerland', ARRAY['egs.edu']::TEXT[], 'egs.edu'),
('Lausanne Hotel School (EHL)', 'Switzerland', ARRAY['ehl.ch']::TEXT[], 'ehl.ch'),
('European University', 'Switzerland', ARRAY['euruni.edu']::TEXT[], 'euruni.edu'),
('Franklin College Switzerland', 'Switzerland', ARRAY['fc.edu']::TEXT[], 'fc.edu'),
('University of Applied Sciences Aargau', 'Switzerland', ARRAY['fh-aargau.ch']::TEXT[], 'fh-aargau.ch'),
('University of Applied Sciences Basel (FHBB )', 'Switzerland', ARRAY['fhbb.ch']::TEXT[], 'fhbb.ch'),
('University of Applied Sciences Chur', 'Switzerland', ARRAY['fh-htachur.ch']::TEXT[], 'fh-htachur.ch'),
('University of Applied Sciences Solothurn Northwestern Switzerland', 'Switzerland', ARRAY['fhso.ch']::TEXT[], 'fhso.ch'),
('Geneva Business School', 'Switzerland', ARRAY['gbs-ge.ch']::TEXT[], 'gbs-ge.ch'),
('Glion Institute of Higher Education', 'Switzerland', ARRAY['glion.edu']::TEXT[], 'glion.edu'),
('Graduate School of Business Administration Zurich (GSBA Zurich)', 'Switzerland', ARRAY['gsba.ch']::TEXT[], 'gsba.ch'),
('Hochschule für Gestaltung und Kunst Zürich', 'Switzerland', ARRAY['hgkz.ch']::TEXT[], 'hgkz.ch'),
('International Culinary Institute (ICI)', 'Switzerland', ARRAY['ici-luzern.com']::TEXT[], 'ici-luzern.com'),
('International Hotel Management Institute', 'Switzerland', ARRAY['imi-luzern.com']::TEXT[], 'imi-luzern.com'),
('International School of Business Management', 'Switzerland', ARRAY['isbm-school.com']::TEXT[], 'isbm-school.com'),
('International University in Geneva', 'Switzerland', ARRAY['iun.ch']::TEXT[], 'iun.ch'),
('Les Roches International School of Hotel Management', 'Switzerland', ARRAY['lesroches.edu']::TEXT[], 'lesroches.edu'),
('Les Roches Gruyère University of Applied Sciences', 'Switzerland', ARRAY['lrguas.ch']::TEXT[], 'lrguas.ch'),
('Fachhochschule Pur', 'Switzerland', ARRAY['phw.info']::TEXT[], 'phw.info'),
('Swiss Business School Zurich (SBS)', 'Switzerland', ARRAY['sbs.edu']::TEXT[], 'sbs.edu'),
('Swiss Management Center', 'Switzerland', ARRAY['swissmc.ch']::TEXT[], 'swissmc.ch'),
('University of Switzerland', 'Switzerland', ARRAY['swissu.org']::TEXT[], 'swissu.org'),
('University Center "César Ritz"', 'Switzerland', ARRAY['uccr.edu']::TEXT[], 'uccr.edu'),
('Libera Università degli Studi di Scienze Umane e Tecnologiche', 'Switzerland', ARRAY['uniludes.ch']::TEXT[], 'uniludes.ch'),
('Victoria University', 'Switzerland', ARRAY['victoria-uni.ch']::TEXT[], 'victoria-uni.ch'),
('Webster University Geneva', 'Switzerland', ARRAY['webster.ch']::TEXT[], 'webster.ch'),
('Zurich University of Applied Sciences Winterthur', 'Switzerland', ARRAY['zhwin.ch']::TEXT[], 'zhwin.ch'),
('EPFL - EPF Lausanne', 'Switzerland', ARRAY['epfl.ch','epfl.edu']::TEXT[], 'epfl.ch'),
('ETHZ - ETH Zurich', 'Switzerland', ARRAY['ethz.ch','eth.edu']::TEXT[], 'ethz.ch'),
('Universita della Svizzera Italiana', 'Switzerland', ARRAY['usi.ch']::TEXT[], 'usi.ch'),
('University of Basel', 'Switzerland', ARRAY['unibas.ch']::TEXT[], 'unibas.ch'),
('University of Fribourg', 'Switzerland', ARRAY['unifr.ch']::TEXT[], 'unifr.ch'),
('University of Geneva', 'Switzerland', ARRAY['unige.ch']::TEXT[], 'unige.ch'),
('Universität Zürich', 'Switzerland', ARRAY['uzh.ch','unizh.ch']::TEXT[], 'uzh.ch'),
('Universität Bern', 'Switzerland', ARRAY['unibe.ch']::TEXT[], 'unibe.ch'),
('Universität Luzern', 'Switzerland', ARRAY['unilu.ch']::TEXT[], 'unilu.ch'),
('Universität St. Gallen (HSG)', 'Switzerland', ARRAY['unisg.ch','student.unisg.ch']::TEXT[], 'unisg.ch'),
('Université de Lausanne', 'Switzerland', ARRAY['unil.ch']::TEXT[], 'unil.ch'),
('Université de Neuchâtel', 'Switzerland', ARRAY['unine.ch']::TEXT[], 'unine.ch'),
('BFH - Bern University of Applied Sciences', 'Switzerland', ARRAY['bfh.ch']::TEXT[], 'bfh.ch'),
('FFHS - Fernfachhochschule Schweiz', 'Switzerland', ARRAY['ffhs.ch']::TEXT[], 'ffhs.ch'),
('FHNW - Fachhochschule Nordwestschweiz', 'Switzerland', ARRAY['fhnw.ch']::TEXT[], 'fhnw.ch'),
('FHS St.Gallen', 'Switzerland', ARRAY['fhsg.ch']::TEXT[], 'fhsg.ch'),
('HEP Vaud - Haute école pédagogique du canton de Vaud', 'Switzerland', ARRAY['hepl.ch']::TEXT[], 'hepl.ch'),
('HEP-BEJUNE - Haute Ecole Pédagogique BEJUNE', 'Switzerland', ARRAY['hep-bejune.ch']::TEXT[], 'hep-bejune.ch'),
('HEP-PH FR - University of Teacher Education Fribourg', 'Switzerland', ARRAY['edufr.ch']::TEXT[], 'edufr.ch'),
('HEPVS - Haute école pédagogique du Valais', 'Switzerland', ARRAY['hepvs.ch']::TEXT[], 'hepvs.ch'),
('HES-SO : UAS Western Switzerland', 'Switzerland', ARRAY['hes-so.ch']::TEXT[], 'hes-so.ch'),
('HfH – University of Applied Sciences of Special Needs Education', 'Switzerland', ARRAY['hfh.ch']::TEXT[], 'hfh.ch'),
('Hochschule Luzern', 'Switzerland', ARRAY['hslu.ch']::TEXT[], 'hslu.ch'),
('HSR - Hochschule für Technik Rapperswil', 'Switzerland', ARRAY['hsr.ch']::TEXT[], 'hsr.ch'),
('HTW Chur - University of Applied Sciences HTW Chur', 'Switzerland', ARRAY['fh-htwchur.ch']::TEXT[], 'fh-htwchur.ch'),
('HWZ - University of Applied Sciences in Business Administration Zurich', 'Switzerland', ARRAY['fh-hwz.ch']::TEXT[], 'fh-hwz.ch'),
('NTB - Hochschule für Technik Buchs', 'Switzerland', ARRAY['ntb.ch']::TEXT[], 'ntb.ch'),
('PH Zug - Pädagogische Hochschule Zug', 'Switzerland', ARRAY['phzg.ch']::TEXT[], 'phzg.ch'),
('PH Zürich - Pädagogische Hochschule Zürich', 'Switzerland', ARRAY['phzh.ch']::TEXT[], 'phzh.ch'),
('PHBern - University of Teacher Education Bern', 'Switzerland', ARRAY['phbern.ch']::TEXT[], 'phbern.ch'),
('PHGR - University of Teacher Education Graubünden', 'Switzerland', ARRAY['ph-gr.ch']::TEXT[], 'ph-gr.ch'),
('PHLU - University of Teacher Education Lucerne', 'Switzerland', ARRAY['phlu.ch']::TEXT[], 'phlu.ch'),
('PHSG - Pädagogische Hochschule St.Gallen', 'Switzerland', ARRAY['phsg.ch']::TEXT[], 'phsg.ch'),
('PHSZ - University of Teacher Education Schwyz', 'Switzerland', ARRAY['phsz.ch']::TEXT[], 'phsz.ch'),
('PHTG - Pädagogische Hochschule Thurgau', 'Switzerland', ARRAY['phtg.ch']::TEXT[], 'phtg.ch'),
('SUPSI - University of Applied Sciences Southern Switzerland', 'Switzerland', ARRAY['supsi.ch']::TEXT[], 'supsi.ch'),
('ZHAW - Zürcher Hochschule für Angewandte Wissenschaften', 'Switzerland', ARRAY['zhaw.ch']::TEXT[], 'zhaw.ch'),
('ZHdK - Zurich University of the Arts', 'Switzerland', ARRAY['zhdk.ch']::TEXT[], 'zhdk.ch'),
('CHUV - University Hospital Lausanne', 'Switzerland', ARRAY['chuv.ch']::TEXT[], 'chuv.ch'),
('HUG - Univ. Hospitals of Geneva', 'Switzerland', ARRAY['hcuge.ch']::TEXT[], 'hcuge.ch'),
('Insel Gruppe', 'Switzerland', ARRAY['insel.ch']::TEXT[], 'insel.ch'),
('University Hospital Zurich', 'Switzerland', ARRAY['unispital.ch']::TEXT[], 'unispital.ch'),
('Institut Le Rosey', 'Switzerland', ARRAY['rosey.ch']::TEXT[], 'rosey.ch'),
('Duale Hochschule Baden-Württemberg', 'Germany', ARRAY['dhbw.de']::TEXT[], 'dhbw.de'),
('Duale Hochschule Baden-Württemberg Heidenheim', 'Germany', ARRAY['heidenheim.dhbw.de']::TEXT[], 'heidenheim.dhbw.de'),
('Duale Hochschule Baden-Württemberg Center for Advanced Studies (CAS)', 'Germany', ARRAY['cas.dhbw.de']::TEXT[], 'cas.dhbw.de'),
('Duale Hochschule Baden-Württemberg Lörrach', 'Germany', ARRAY['dhbw-loerrach.de']::TEXT[], 'dhbw-loerrach.de'),
('Duale Hochschule Baden-Württemberg Mosbach', 'Germany', ARRAY['dhbw-mosbach.de','mosbach.dhbw.de']::TEXT[], 'dhbw-mosbach.de'),
('Duale Hochschule Baden-Württemberg Ravensburg', 'Germany', ARRAY['ravensburg.dhbw.de']::TEXT[], 'ravensburg.dhbw.de'),
('Duale Hochschule Baden-Württemberg Stuttgart', 'Germany', ARRAY['dhbw-stuttgart.de']::TEXT[], 'dhbw-stuttgart.de'),
('Duale Hochschule Baden-Württemberg Villingen-Schwenningen', 'Germany', ARRAY['dhbw-vs.de']::TEXT[], 'dhbw-vs.de'),
('Duale Hochschule Baden-Württemberg Heilbronn', 'Germany', ARRAY['heilbronn.dhbw.de']::TEXT[], 'heilbronn.dhbw.de'),
('Duale Hochschule Baden-Württemberg Karlsruhe', 'Germany', ARRAY['dhbw-karlsruhe.de','karlsruhe.dhbw.de']::TEXT[], 'dhbw-karlsruhe.de'),
('Duale Hochschule Baden-Wuerttemberg Mannheim', 'Germany', ARRAY['dhbw-mannheim.de','mannheim.dhbw.de']::TEXT[], 'dhbw-mannheim.de'),
('Hochschule Hannover', 'Germany', ARRAY['hs-hannover.de','stud.hs-hannover.de']::TEXT[], 'hs-hannover.de'),
('Staatliche Studienakademie Bautzen', 'Germany', ARRAY['ba-bautzen.de']::TEXT[], 'ba-bautzen.de'),
('HTL Villach', 'Austria', ARRAY['htl-villach.at','edu.htl-villach.at']::TEXT[], 'htl-villach.at'),
('HTL WELS', 'Austria', ARRAY['htl-wels.at']::TEXT[], 'htl-wels.at'),
('Technische Hochschule Mittelhessen', 'Germany', ARRAY['thm.de']::TEXT[], 'thm.de'),
('Hochschule für Wirtschaft und Gesellschaft Ludwigshafen', 'Germany', ARRAY['hwg-lu.de']::TEXT[], 'hwg-lu.de'),
('Leuphana Universität Lüneburg', 'Germany', ARRAY['leuphana.de']::TEXT[], 'leuphana.de'),
('Ostbayerische Technische Hochschule Amberg-Weiden', 'Germany', ARRAY['oth-aw.de']::TEXT[], 'oth-aw.de'),
('Musikhochschule Lübeck', 'Germany', ARRAY['mh-luebeck.de']::TEXT[], 'mh-luebeck.de'),
('Hochschule für Musik und Theater München', 'Germany', ARRAY['musikhochschule-muenchen.de','hmtm.de']::TEXT[], 'musikhochschule-muenchen.de'),
('Universität der Künste Berlin', 'Germany', ARRAY['udk-berlin.de']::TEXT[], 'udk-berlin.de'),
('Hochschule für Musik und Tanz Köln', 'Germany', ARRAY['hfmt-koeln.de']::TEXT[], 'hfmt-koeln.de'),
('Hochschule für Musik Carl Maria von Weber', 'Germany', ARRAY['hfmdd.de']::TEXT[], 'hfmdd.de'),
('Hochschule für Musik und Darstellende Kunst Stuttgart', 'Germany', ARRAY['hmdk-stuttgart.de']::TEXT[], 'hmdk-stuttgart.de'),
('Hochschule für Künste Bremen', 'Germany', ARRAY['hfk-bremen.de','hfk2020.de']::TEXT[], 'hfk-bremen.de'),
('Hochschule für Musik und Theater „Felix Mendelssohn Bartholdy“ Leipzig', 'Germany', ARRAY['hmt-leipzig.de']::TEXT[], 'hmt-leipzig.de'),
('Hochschule für Musik, Theater und Medien Hannover', 'Germany', ARRAY['hmtm-hannover.de']::TEXT[], 'hmtm-hannover.de'),
('Hochschule für Musik Detmold', 'Germany', ARRAY['hfm-detmold.de']::TEXT[], 'hfm-detmold.de'),
('Deutsche Universität für Verwaltungswissenschaften Speyer', 'Germany', ARRAY['uni-speyer.de']::TEXT[], 'uni-speyer.de'),
('Europa-Universität Viadrina', 'Germany', ARRAY['europa-uni.de']::TEXT[], 'europa-uni.de'),
('Frankfurt School of Finance & Management', 'Germany', ARRAY['fs.de','fs-students.de']::TEXT[], 'fs.de'),
('IMD - International Institute for Management Development', 'Switzerland', ARRAY['imd.org']::TEXT[], 'imd.org'),
('Hochschule für Fernsehen und Film München', 'Germany', ARRAY['hff-muenchen.de']::TEXT[], 'hff-muenchen.de'),
('UMIT Tirol', 'Austria', ARRAY['umit-tirol.at']::TEXT[], 'umit-tirol.at'),
('IST-Hochschule fur Management', 'Germany', ARRAY['ist-hochschule.de']::TEXT[], 'ist-hochschule.de'),
('EBS Universität', 'Germany', ARRAY['ebs.edu']::TEXT[], 'ebs.edu'),
('Hochschule RheinMain', 'Germany', ARRAY['hs-rm.de']::TEXT[], 'hs-rm.de'),
('Rosenheim University of Applied Sciences', 'Germany', ARRAY['th-rosenheim.de']::TEXT[], 'th-rosenheim.de'),
('Karl-Schiller-Berufskolleg (KSBK)', 'Germany', ARRAY['ksbk-do.de']::TEXT[], 'ksbk-do.de'),
('Westphalian University of Applied Sciences', 'Germany', ARRAY['w-hs.de']::TEXT[], 'w-hs.de'),
('Technische Hochschule Ulm', 'Germany', ARRAY['thu.de']::TEXT[], 'thu.de'),
('Brandenburg University of Technology Cottbus - Senftenberg', 'Germany', ARRAY['b-tu.de']::TEXT[], 'b-tu.de')
) AS v(name, country, email_domains, external_ref)
WHERE NOT EXISTS (
  SELECT 1 FROM public.universities existing
  WHERE existing.source <> 'hipo'
    AND existing.email_domains && v.email_domains
)
ON CONFLICT (source, external_ref) DO UPDATE
  SET name = EXCLUDED.name, country = EXCLUDED.country,
      email_domains = EXCLUDED.email_domains,
      last_scraped_at = now(), updated_at = now();
