🚀 Starting Learnstation in Unified Mode...
----------------------------------------
🧹 Clearing ports 8000 and 8080...
  ↳ Port 8000 cleared.
  ↳ Port 8080 cleared.
----------------------------------------
Initializing Backend (FastAPI)...
✅ Backend scheduled to start on http://localhost:8000
----------------------------------------
Initializing Frontend (Vite)...
✅ Frontend scheduled to start on http://localhost:8080
----------------------------------------
Press Ctrl+C to stop both servers.
----------------------------------------

Shutting down servers...
